version: '3'
services:
  nginx-proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes :
      - /etc/letsencrypt:/etc/letsencrypt
  mapisto-api:
    image: "mapisto/mapisto-api:0.1.1"
    environment: 
      MAPISTO_DB_HOST : database
    env_file: 
      - db_access.env
      - mapisto_config.env
  database:
    image: postgres:12-alpine
    volumes: 
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
