version: "3"
services:
  nginx-proxy:
    image: mapisto/mapisto-front:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx_conf.d:/etc/nginx/conf.d
  mapisto-api:
    image: mapisto/mapisto-api:latest
    environment:
      MAPISTO_DB_HOST: database
    env_file:
      - conf.env
    ports:
      - 127.0.0.1:5000:5000
  database:
    image: postgres:12-alpine
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
